apiVersion: v1
kind: Pod
metadata:
  name: myaffinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gke-cluster-1-default-pool-1da65713-b3xj
  containers:
  - name: myaffinity
    image: {{ .Values.image }}
