apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-topology
  labels:
    app: redis-topology
spec:
  replicas: 9
  selector:
    matchLabels:
      app: redis-topology
  template:
    metadata:
      labels:
        app: redis-topology
    spec: 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - asia-northeast3-a
                - asia-northeast3-b
                - asia-northeast3-c
      containers:
      - name: redis-topology
        image: {{ .Values.redis_img }}
        ports:
        - containerPort: 6379
          hostPort: 6379

